/**
 * Multilingual button vocabulary (24 EU languages + NO, TR, RU, UK, CA, EU) for the generic banner heuristic.
 * Labels are normalised first (see text.ts): lower case, apostrophes removed, punctuation → spaces.
 * Entries are regex sources, matched with Unicode-aware word boundaries. `W` = rest of a word.
 */
const W = '\\p{L}*';

/** Paid / subscription options – never clicked. */
export const PAY = [
  '\\d+[.,]\\d{2}',
  '€',
  'eur',
  'abos?',
  `abonn${W}`,
  `subscri${W}`,
  'pur',
  `werbefrei${W}`,
  'ohne werbung',
  'ad free',
  'without (ads|advertising)',
  'sans (pub|publicité)',
  'senza pubblicità',
  'sin publicidad',
  'zonder advertenties',
  `reklamfri${W}`,
  'bez reklam',
  'contentpass',
  'jetzt sichern',
  'kaufen',
  'buy',
  'premium',
];

/** Account actions – never clicked. */
export const LOGIN = [
  'log ?in',
  'sign ?(in|up)',
  'register',
  'anmelden',
  'einloggen',
  'registrieren',
  'konto',
  'se connecter',
  'connexion',
  'sinscrire',
  'iniciar sesión',
  'registrarse',
  'accedi',
  'registrati',
  'inloggen',
  'registreren',
  `zaloguj${W}`,
  'logga in',
  'log ind',
  'kirjaudu',
];

/** Explicit rejection. */
export const REJECT = [
  `reject${W}`,
  `decline${W}`,
  'deny',
  `refuse${W}`,
  'disagree',
  'no thanks',
  'not now',
  'opt out',
  `object${W}`,
  `widersprech${W}`,
  'sopposer',
  'oponerse',
  'opporsi',
  'bezwaar',
  'ablehnen',
  'verweigern',
  'refuser',
  'je refuse',
  'non merci',
  `afwij${W}`,
  `rechaz${W}`,
  'denegar',
  `rifiut${W}`,
  'nega',
  `rejeit${W}`,
  `recus${W}`,
  `rebutj${W}`,
  `weiger${W}`,
  `odrzu${W}`,
  `odmítn${W}`,
  `odmiet${W}`,
  `zavrni${W}`,
  `odbij${W}`,
  `elutasít${W}`,
  `refuz${W}`,
  `resping${W}`,
  `отхвърл${W}`,
  `откаж${W}`,
  'απόρριψη',
  'απορρίπτω',
  'διαφωνώ',
  'avvisa',
  'neka',
  `afvis${W}`,
  `avvis${W}`,
  'hylkää',
  'keeldu',
  'noraidīt',
  'atmesti',
  'reddet',
  'отклонить',
  'отказаться',
  'відхилити',
];

/** Negations: "do not accept", "nicht erlauben", "no acepto" … */
export const NEGATION = [
  'no',
  'not',
  'dont',
  'nie',
  'niet',
  'geen',
  'ne pas',
  'nicht',
  'nichts',
  `kein${W}`,
  'non',
  'aucun',
  'nu',
  'ne',
  'não',
  'nem',
  'ei',
  'ikke',
  'inte',
  'не',
  'μην',
  'δεν',
  'δε',
];

/** "Continue without (accepting)". */
export const WITHOUT = ['without', 'zonder', 'ohne', 'sans', 'sin', 'senza', 'sem', 'bez', 'без', 'χωρίς', 'utan', 'uden', 'uten', 'ilman', 'ilma', 'olmadan'];

/** Necessary / essential cookies only. */
export const NECESSARY = [
  'necessary',
  'essential',
  'required',
  'technical',
  'strictly',
  `minimal${W}`,
  'basic',
  'basis',
  `function${W}`,
  `funktion${W}`,
  `statisti${W}`,
  'beperkt',
  'essentiële',
  `notwendig${W}`,
  `essenziell${W}`,
  `essentiell${W}`,
  `erforderlich${W}`,
  `technisch${W}`,
  'nécessaires?',
  'essentiels?',
  'strictement',
  `necesari${W}`,
  `esencial${W}`,
  'técnicas?',
  `necessar${W}`,
  `essenzial${W}`,
  `tecnic${W}`,
  'necessários?',
  `noodzakelijk${W}`,
  'vereiste',
  `functionele`,
  `niezbędn${W}`,
  `wymagan${W}`,
  `nezbytn${W}`,
  `nevyhnutn${W}`,
  `nujn${W}`,
  `nužn${W}`,
  `szükséges${W}`,
  `esențial${W}`,
  `необходим${W}`,
  `απαραίτητ${W}`,
  `nödvändig${W}`,
  `nødvendig${W}`,
  `välttämät${W}`,
  `vajalik${W}`,
  `nepieciešam${W}`,
  `būtin${W}`,
  'gerekli',
  'zorunlu',
];

/** "Only" – "accept only …" is never maximum consent. */
export const ONLY = ['only', 'nur', 'ausschließlich', 'enkel', 'solo', 'sólo', 'seulement', 'uniquement', 'alleen', 'tylko', 'jen', 'iba', 'samo', 'csak', 'doar', 'endast', 'kun', 'bare', 'vain', 'ainult', 'tikai', 'tik', 'sadece', 'только', 'apenas', 'μόνο'];

/** Withdrawing consent. */
export const REVOKE = ['withdraw', 'revoke', `widerruf${W}`, 'zurücksetzen', 'zurückziehen', 'revocar', 'retirer', `revoca${W}`, 'intrekken', 'wycofaj', 'odvolat'];

/** Age gates and similar confirmations that are not about cookies. */
export const AGE = [
  '\\d+ ?\\+',
  'i am (at least|over|\\d)',
  'or older',
  'ik ben (\\d|ouder|onder|minimaal)',
  'ich bin (über|\\d|mindestens|volljährig)',
  'jai plus',
  'tengo (más|\\d)',
  'ho più',
  'years old',
  'jahre',
  'jaar',
  'älter',
  'ans',
  'años',
  'anni',
  'enter',
  'betreten',
];

/** Accept / save the current selection (not "all") – part of the settings flow, never the main accept. */
export const SAVE = [
  '(accept|allow|confirm|save|submit|use) (my |the |current )?(selection|selected|choices?|preferences|settings)',
  'save (and|&) (close|exit|continue)',
  '(save|store) (cookie |my )?(settings|preferences|choices)',
  '(auswahl|einstellungen|präferenzen) (speichern|akzeptieren|bestätigen|übernehmen|erlauben|zulassen)',
  'speichern',
  'bestätigen',
  'meine auswahl',
  '(enregistrer|valider|confirmer|accepter) (mes |les )?(choix|préférences|paramètres|la sélection|sélection)',
  '(guardar|confirmar|aceptar|permitir) (la )?(selección|configuración|preferencias|mis preferencias)',
  'guardar',
  '(salva|conferma|accetta|consenti) (le )?(scelte|preferenze|selezione|selezionati)',
  '(guardar|confirmar|aceitar|permitir) (as )?(preferências|seleção|escolhas)',
  '(selectie|voorkeuren|keuze|instellingen) (opslaan|bevestigen|accepteren|toestaan)',
  'opslaan',
  'bewaar',
  '(zapisz|potwierdź|zaakceptuj|akceptuj) (wybrane|ustawienia|wybór|moje)',
  'potwierdzam wybrane',
  'uložit',
  'potvrdit (výběr|volbu)',
  'povolit (výběr|vybrané)',
  'uložiť',
  'shrani',
  'spremi',
  'mentés',
  'salvează',
  'запази',
  'αποθήκευση',
  'spara',
  'tillåt (urval|valda)',
  'gem (valg|indstillinger)',
  'tillad (valgte|udvalgte)',
  'lagre',
  'tallenna',
  'salvesta',
  'saglabāt',
  'išsaugoti',
  'kaydet',
  'сохранить',
  'зберегти',
];

/** Accepting. Combined with ALL → "accept all". */
export const ACCEPT = [
  // EN
  'accept(s|ed|ing)?',
  'agree(d|s)?',
  'allow(s|ed|ing)?',
  'i consent',
  'enable all',
  'yes',
  'sounds good',
  'continue (and|&) accept',
  'continue (with|using) (all |recommended |the )?cookies',
  'continue with (all|recommended)',
  '(i )?confirm all',
  'consent (to all|and continue|to cookies)',
  'use recommended (settings|cookies)',
  // DE
  `akzeptier${W}`,
  'annehmen',
  `zustimm${W}`,
  'stimme zu',
  'zulassen',
  'erlauben',
  'einverstanden',
  'einwilligen',
  'einwilligung',
  'alle aktivieren',
  // FR
  'accepter',
  'jaccepte',
  'autoriser',
  'daccord',
  'je suis daccord',
  'consentir',
  'oui',
  `acceptez${W}`,
  // ES / CA / EU
  'acept(ar|o|a|amos|e)',
  `permitir${W}`,
  'de acuerdo',
  'estoy de acuerdo',
  'consiento',
  'sí',
  'accept(ar|o|a)',
  `permet${W}`,
  'estic dacord',
  'onartu',
  // IT
  'accett(a|o|are|iamo)',
  'consenti',
  'consento',
  'acconsento',
  'va bene',
  // PT
  'aceit(ar|o|e|a)',
  'concord(o|ar)',
  'autoriz(ar|o)',
  // NL
  'accepteer',
  'accepteren',
  'akkoord',
  'ga akkoord',
  'toestaan',
  'sta (\\p{L}+ )?toe',
  'aanvaard(en)?',
  'ja',
  'is goed',
  'prima',
  // PL
  `akceptuj${W}`,
  'zaakceptuj',
  'zgadzam się',
  'zgoda',
  'wyrażam zgodę',
  'zezwól',
  'tak',
  `potwierdzam wszystk${W}`,
  // CS / SK
  `přijm${W}`,
  `souhlas${W}`,
  'povolit',
  'prijať',
  'prijímam',
  `súhlas${W}`,
  'povoliť',
  // SL / HR
  `sprejm${W}`,
  'strinjam se',
  'dovoli',
  `prihvat${W}`,
  'slažem se',
  'dopusti',
  'dozvoli',
  // HU / RO
  `elfogad${W}`,
  `engedélyez${W}`,
  'egyetértek',
  'hozzájárulok',
  'acceptă',
  'acceptați',
  'acceptare',
  'sunt de acord',
  'permite',
  // BG / EL
  `прием${W}`,
  `съглас${W}`,
  `разреш${W}`,
  'αποδοχή',
  'αποδέχομαι',
  'συμφωνώ',
  'επιτρέπω',
  'αποδεχτείτε',
  // Nordic
  'acceptera',
  `godkänn${W}`,
  'tillåt',
  `accepter${W}`,
  'acceptér',
  'tillad',
  `godta${W}`,
  `aksepter${W}`,
  'tillat',
  `hyväksy${W}`,
  'salli',
  // Baltic
  `nõustu${W}`,
  'aktsepteeri',
  'luba',
  'piekrītu',
  'pieņemt',
  'atļaut',
  'sutinku',
  'priimti',
  'leisti',
  // MT / GA
  'naċċetta',
  'aċċetta',
  `glac${W}`,
  // TR / RU / UK
  `kabul${W}`,
  'izin ver',
  'onayla',
  'принять',
  'принимаю',
  'согласен',
  'согласна',
  'прийняти',
  'погоджуюсь',
];

/** "All / everything" – turns ACCEPT into ACCEPT_ALL. Also the free option on consent-or-pay walls. */
export const ALL = [
  'all',
  'everything',
  'alle',
  'alles',
  'tout',
  'tous',
  'toutes',
  'todo',
  'todas',
  'todos',
  'tudo',
  'tutti',
  'tutto',
  'tutte',
  'totes',
  'dena',
  `wszystk${W}`,
  'vše',
  'všechny',
  `všetk${W}`,
  'vse',
  'vsa',
  'sve',
  `összes${W}`,
  'mind',
  `minden${W}`,
  'tot',
  'toate',
  'всички',
  'όλων',
  'όλα',
  'alla',
  'kaikki',
  `kõik${W}`,
  'visu',
  'visas',
  'visus',
  'viską',
  'tümünü',
  'hepsini',
  'все',
  'всё',
  'усі',
  'recommended',
  'javasolt',
  'aanbevolen',
  `empfohlen${W}`,
  'recommandés?',
  'mit werbung',
  'with (ads|advertising)',
  'avec (publicité|pub)',
  'con (pubblicità|publicidad)',
  'met advertenties',
  'kostenlos',
  'gratis',
  'for free',
];

/** Acknowledging a notice that offers no choice: OK / got it / understood. */
export const ACKNOWLEDGE = [
  'ok',
  'okay',
  'okey',
  'okej',
  'oké',
  'ок',
  'got it',
  'i understand',
  'understood',
  'verstanden',
  'alles klar',
  'geht klar',
  'compris',
  'jai compris',
  'entendido',
  'entendi',
  'capito',
  'ho capito',
  'begrepen',
  'rozumiem',
  'rozumím',
  'razumem',
  'razumijem',
  'értem',
  'am înțeles',
  'разбрах',
  'κατάλαβα',
  'jag förstår',
  'forstået',
  'forstått',
  'selvä',
  'ymmärrän',
  'sain aru',
  'sapratu',
  'supratau',
  'anladım',
  'понятно',
  'зрозуміло',
];

/** Selecting every toggle in a settings dialog (used by the settings flow). */
export const SELECT_ALL = [
  'select all',
  'alle (cookies )?auswählen',
  'alles auswählen',
  'tout sélectionner',
  'alles selecteren',
  'seleccionar todo',
  'seleziona tutt[oi]',
  `zaznacz wszystk${W}`,
  'markera alla',
  'vælg alle',
  'velg alle',
  'valitse kaikki',
];

/** Opening settings / more options / information. */
export const SETTINGS = [
  'settings',
  'preferences',
  'consent (settings|options|details|preferences|manager|tool)',
  'manage consent',
  'customi[sz]e',
  `manage${W}`,
  'options',
  `more (options|choices|info${W}|details)`,
  'learn more',
  'details',
  'configure',
  'einstellungen',
  `einwilligungs ${W}`,
  'anpassen',
  'verwalten',
  'mehr (erfahren|infos?|optionen)',
  `${W}optionen`,
  `individuell${W}`,
  'paramètres',
  'paramétrer',
  'personnaliser',
  'gérer',
  'en savoir plus',
  `configura${W}`,
  `personaliz${W}`,
  `gestion${W}`,
  'más información',
  'impostazioni',
  'personalizza',
  'gestisci',
  'preferenze',
  'opções',
  'definições',
  'instellingen',
  'aanpassen',
  'beheren',
  'voorkeuren',
  'ustawienia',
  'dostosuj',
  'zarządzaj',
  'nastavení',
  'přizpůsobit',
  'nastavenia',
  'nastavitve',
  'postavke',
  'beállítások',
  `testreszab${W}`,
  'setări',
  'personalizează',
  'настройки',
  'ρυθμίσεις',
  'περισσότερες επιλογές',
  'επιλογές',
  'inställningar',
  'anpassa',
  'indstillinger',
  'tilpas',
  'innstillinger',
  'asetukset',
  'muokkaa',
  'seaded',
  'iestatījumi',
  'nustatymai',
  'ayarlar',
  'параметры',
  'налаштування',
];
